import Mod from '@wayward/game/mod/Mod';
import BetterCraftingPanel from './src/BetterCraftingDialog';
import { ActionType } from "@wayward/game/game/entity/action/IAction";
import type { IActionHandlerApi } from "@wayward/game/game/entity/action/IAction";
import type Entity from "@wayward/game/game/entity/Entity";
import { ItemType } from "@wayward/game/game/item/IItem";
import type { IBetterCraftingRequestStatus, IBulkActionAbortRequest, IBulkCraftRequest, ICraftApprovalResponse, ICraftSelectionRequest, IDismantleRequest } from "./src/multiplayer/BetterCraftingProtocol";
type ActivationMode = "holdHotkeyToBypass" | "holdHotkeyToAccess";
type ActivationHotkey = "Shift" | "Control" | "Alt";
type CloseHotkey = string;
interface IBetterCraftingGlobalData {
    activationMode: ActivationMode;
    activationHotkey: ActivationHotkey;
    closeHotkey: CloseHotkey;
    safeCrafting: boolean;
    debugLogging: boolean;
}
interface IVanillaCraftBypassPermitRequest {
    requestId: number;
    itemType: ItemType;
    requiredItemIds: number[];
    consumedItemIds: number[];
    baseItemId?: number;
}
export default class BetterCrafting extends Mod {
    static readonly INSTANCE: BetterCrafting;
    globalData: IBetterCraftingGlobalData;
    panel?: BetterCraftingPanel;
    bypassIntercept: boolean;
    private shiftHeld;
    private isBulkCrafting;
    private bulkAbortController;
    private nextMultiplayerRequestId;
    private readonly pendingApprovals;
    private readonly pendingVanillaBypasses;
    private readonly serverCraftPasses;
    private readonly serverVanillaBypassPermits;
    private readonly settingsOptionUnsubscribers;
    initializeGlobalData(data: unknown): IBetterCraftingGlobalData;
    onInitialize(): void;
    private clearSettingsOptionSubscriptions;
    onLoad(): void;
    onUnload(): void;
    private get settings();
    private normalizeSettings;
    private clearHeldHotkeyState;
    private isConfiguredHotkey;
    private isTypingInEditableControl;
    private isActivationHotkeyHeld;
    private shouldOpenBetterCrafting;
    private shouldAbortForHealthLoss;
    private getItemId;
    private getCraftReusableItems;
    private applyCraftReusableDurability;
    private get debugLoggingEnabled();
    private debugLog;
    private onKeyDown;
    private onKeyUp;
    private onBlur;
    private isRemoteMultiplayerClient;
    private showMultiplayerMessage;
    private clearPendingApprovals;
    private clearPendingVanillaBypasses;
    private getTypeDebugName;
    private formatSelectionFailureMessage;
    private logSelectionFailure;
    private createSelectionFailure;
    private requestApproval;
    handleCraftApproval(approval: ICraftApprovalResponse): void;
    private sendApproval;
    private sendStatus;
    handleMultiplayerStatus(status: IBetterCraftingRequestStatus): void;
    private getPlayerKey;
    private getPlayerFromConnection;
    private getConnectionForPlayer;
    private getEntityIdentifier;
    private getLiveServerPass;
    private hasLiveServerPass;
    private rejectLivePass;
    private buildCraftArgsSummary;
    private reportBlockedRemoteCraft;
    abortServerRequest(connection: any, request: IBulkActionAbortRequest): void;
    processVanillaBypassPermit(connection: any, request: IVanillaCraftBypassPermitRequest): void;
    private getVanillaCraftActionDetails;
    private areNumberArraysEqual;
    private consumeVanillaBypassPermit;
    private trySendVanillaBypassPermit;
    private replayApprovedVanillaBypass;
    private consumeServerPass;
    private ensurePanel;
    private findMatchingItems;
    private buildRecipeInventorySnapshot;
    private buildSlotSelectionMap;
    private resolveSelectedItems;
    private resolveCraftSelection;
    private partitionComponentSelection;
    private resolveBulkSelection;
    private resolveDismantleTargets;
    private executeCraft;
    private waitForTurnEnd;
    private waitForActionDelayClear;
    private abortBulkCraft;
    private canUseForDismantle;
    private registerBulkInterruptHooks;
    private executeBulkCraft;
    private executeDismantle;
    processCraftRequest(connection: any, request: ICraftSelectionRequest): void;
    processBulkCraftRequest(connection: any, request: IBulkCraftRequest): void;
    processDismantleRequest(connection: any, request: IDismantleRequest): void;
    private isVanillaBypassCraftRequested;
    onPreExecuteAction(host: any, actionType: ActionType, actionApi: IActionHandlerApi<Entity>, args: any[]): false | void;
    private handleServerPreExecute;
    private handleClientPreExecute;
    onPostExecuteAction(host: any, actionType: ActionType, actionApi: IActionHandlerApi<Entity>, args: any[]): void;
}
export {};
