import Mod from '@wayward/game/mod/Mod';
import BetterCraftingPanel from './src/BetterCraftingDialog';
import { ActionType } from "@wayward/game/game/entity/action/IAction";
import type { IActionHandlerApi } from "@wayward/game/game/entity/action/IAction";
import type Entity from "@wayward/game/game/entity/Entity";
import type { IBetterCraftingRequestStatus, IBulkActionAbortRequest, IBulkCraftRequest, ICraftApprovalResponse, ICraftSelectionRequest, IDismantleRequest } from "./src/multiplayer/BetterCraftingProtocol";
type ActivationMode = "holdHotkeyToBypass" | "holdHotkeyToAccess";
type ActivationHotkey = "Shift" | "Control" | "Alt";
interface IBetterCraftingGlobalData {
    activationMode: ActivationMode;
    activationHotkey: ActivationHotkey;
    unsafeBulkCrafting: boolean;
    debugLogging: boolean;
}
export default class BetterCrafting extends Mod {
    static readonly INSTANCE: BetterCrafting;
    globalData: IBetterCraftingGlobalData;
    panel?: BetterCraftingPanel;
    bypassIntercept: boolean;
    private shiftHeld;
    private isBulkCrafting;
    private legacyUnsafeCraftingSeed;
    private bulkAbortController;
    private nextMultiplayerRequestId;
    private readonly pendingApprovals;
    private readonly serverCraftPasses;
    initializeGlobalData(data: unknown): IBetterCraftingGlobalData;
    onInitialize(): void;
    onLoad(): void;
    onUnload(): void;
    private get settings();
    private normalizeSettings;
    private clearHeldHotkeyState;
    private isConfiguredHotkey;
    private isActivationHotkeyHeld;
    private shouldOpenBetterCrafting;
    private shouldAbortForHealthLoss;
    private getItemId;
    private get debugLoggingEnabled();
    private debugLog;
    private onKeyDown;
    private onKeyUp;
    private onBlur;
    private consumeLegacyUnsafeCraftingSeed;
    private isRemoteMultiplayerClient;
    private clearPendingApprovals;
    private getTypeDebugName;
    private formatSelectionFailureMessage;
    private logSelectionFailure;
    private createSelectionFailure;
    private requestApproval;
    handleCraftApproval(approval: ICraftApprovalResponse): void;
    private sendApproval;
    handleMultiplayerStatus(status: IBetterCraftingRequestStatus): void;
    private getPlayerKey;
    private getPlayerFromConnection;
    abortServerRequest(connection: any, request: IBulkActionAbortRequest): void;
    private consumeServerPass;
    private ensurePanel;
    private findMatchingItems;
    private buildRecipeInventorySnapshot;
    private buildSlotSelectionMap;
    private resolveSelectedItems;
    private resolveCraftSelection;
    private partitionComponentSelection;
    private resolveBulkSelection;
    private resolveDismantleTargets;
    private executeCraft;
    private waitForTurnEnd;
    private waitForActionDelayClear;
    private abortBulkCraft;
    private canUseForDismantle;
    private registerBulkInterruptHooks;
    private executeBulkCraft;
    private executeDismantle;
    processCraftRequest(connection: any, request: ICraftSelectionRequest): void;
    processBulkCraftRequest(connection: any, request: IBulkCraftRequest): void;
    processDismantleRequest(connection: any, request: IDismantleRequest): void;
    onPreExecuteAction(host: any, actionType: ActionType, actionApi: IActionHandlerApi<Entity>, args: any[]): false | void;
}
export {};
