import Component from "@wayward/game/ui/component/Component";
import { ItemType, RecipeLevel } from "@wayward/game/game/item/IItem";
import type Item from "@wayward/game/game/item/Item";
import type { IBulkCraftRequest, ICraftSelectionRequest, IDismantleRequest } from "./multiplayer/BetterCraftingProtocol";
type CraftCallback = (itemType: ItemType, required: Item[] | undefined, consumed: Item[] | undefined, base: Item | undefined) => Promise<void>;
type BulkCraftCallback = (itemType: ItemType, quantity: number, excludedIds: Set<number>) => Promise<void>;
type DismantleCallback = (items: Item[], requiredItem?: Item) => Promise<void>;
export interface IBetterCraftingSettings {
    activationMode: "holdHotkeyToBypass" | "holdHotkeyToAccess";
    activationHotkey: "Shift" | "Control" | "Alt";
    unsafeBulkCrafting: boolean;
    debugLogging: boolean;
}
type SettingsAccessor = () => IBetterCraftingSettings;
interface ICraftExecutionDiagnostics {
    itemType: ItemType;
    requiredIds: number[];
    consumedIds: number[];
    baseId: number | undefined;
    slots: Array<{
        slotIndex: number;
        requiredAmount?: number;
        consumedAmount?: number;
        selectedIds: number[];
        consumedIds: number[];
        requiredIds: number[];
        splitConsumedIds?: number[];
        splitUsedIds?: number[];
    }>;
}
export declare const STAMINA_COST_PER_LEVEL: Partial<Record<RecipeLevel, number>>;
export default class BetterCraftingPanel extends Component {
    itemType: number;
    private panelMode;
    private tabBar;
    private closeBtn;
    private scrollContent;
    private normalScrollInner;
    private bulkScrollInner;
    private _sectionResizeObserver?;
    private _sectionResizeRafId?;
    private recipe?;
    private dismantleDescription?;
    private onCraftCallback;
    private onBulkCraftCallback;
    private onDismantleCallback;
    private getSettings;
    private craftBtn;
    private validationMsg?;
    private selectedItems;
    private splitSelectedItems;
    private sectionCounters;
    private _pendingSelectionIds;
    private _pendingSplitSelectionIds;
    private bcTooltipEl;
    private _hoveredItem;
    private _hoveredDisplayName;
    private _hoveredMouseX;
    private _hoveredMouseY;
    private shiftHeld;
    private _inventoryRefreshTimer;
    private _inventoryRefreshQueued;
    private _inventoryWatchHandlers;
    private activeTab;
    private normalTabBtn;
    private bulkTabBtn;
    private normalBody;
    private normalStaticContent;
    private normalFooter;
    private bulkBody;
    private bulkStaticContent;
    private bulkFooter;
    private bulkExcludedIds;
    private bulkPreserveDurabilityBySlot;
    private bulkPinnedToolSelections;
    private bulkPinnedUsedSelections;
    private _lastBulkItemType;
    private bulkQuantity;
    private bulkQtyInputEl;
    private bulkMaxLabel;
    private bulkCraftBtnEl;
    private bulkUnsafeToggleEl;
    private bulkUnsafeToggleWrap;
    private bulkScrollContent;
    private _bulkContentDirty;
    private bulkStopBtn;
    private bulkQtyRow;
    private bulkProgressEl;
    private onBulkAbortCallback;
    private onPanelHideCallback;
    private bulkProgressVerb;
    private unsafeCraftingEnabled;
    private lastBulkResolutionMessage?;
    private destroyed;
    private dismantleExcludedIds;
    private dismantleRequiredSelection?;
    private dismantleSelectedItemType?;
    private preserveDismantleRequiredDurability;
    private helpBoxExpanded;
    private get activationHotkey();
    private get debugLoggingEnabled();
    isUnsafeCraftingEnabled(): boolean;
    showMultiplayerMessage(message: string): void;
    private debugLog;
    consumeLastBulkResolutionMessage(): string | undefined;
    private setUnsafeCraftingEnabled;
    private resetUnsafeCraftingEnabled;
    private getPanelScale;
    private anchorPanelToViewport;
    private getMinDimensionPx;
    private beginResize;
    private isConfiguredHotkey;
    private updateActivationHotkeyState;
    private readonly _onShiftDown;
    private readonly _onShiftUp;
    private readonly _onBlur;
    constructor(onCraft: CraftCallback, onBulkCraft: BulkCraftCallback, onDismantle: DismantleCallback, getSettings: SettingsAccessor, initialUnsafeCrafting?: boolean);
    destroyListeners(): void;
    private canAccessElements;
    private _subscribeInventoryWatch;
    private _unsubscribeInventoryWatch;
    private scheduleInventoryRefresh;
    private flushQueuedInventoryRefresh;
    isDismantleMode(): boolean;
    isSameDismantleType(itemType: ItemType): boolean;
    requiresDismantleRequiredItem(): boolean;
    resolveDismantleRequiredSelection(): Item | undefined;
    private showSelectionChangedError;
    private sanitizeSelectedItems;
    private supplementSelectedItems;
    private getSelectionFailureMessage;
    private setBulkResolutionFailure;
    buildCraftRequestDiagnostics(request: ICraftSelectionRequest): Record<string, unknown>;
    buildCraftExecutionDiagnostics(itemType: ItemType, slotSelections: Iterable<readonly Item[]>, base: Item | undefined): ICraftExecutionDiagnostics;
    buildCurrentNormalCraftSelectionState(): Record<string, unknown>;
    buildBulkRequestDiagnostics(request: IBulkCraftRequest): Record<string, unknown>;
    private serializeSlotSelection;
    serializeCraftSelectionRequest(requestId: number): ICraftSelectionRequest | undefined;
    private resolveCurrentCraftSelection;
    serializeBulkCraftRequest(requestId: number, quantity: number): IBulkCraftRequest | undefined;
    serializeDismantleRequest(requestId: number, quantity: number): IDismantleRequest | undefined;
    openDismantle(item: Item): void;
    private applyPanelModeLayout;
    private switchTab;
    showPanel(): void;
    hidePanel(): void;
    get panelVisible(): boolean;
    setBulkAbortCallback(cb: (() => void) | null): void;
    setPanelHideCallback(cb: (() => void) | null): void;
    onBulkCraftStart(total: number, verb?: string): void;
    setBulkProgress(current: number, total: number, verb?: string): void;
    onBulkCraftEnd(): void;
    private updateHighlights;
    private clearHighlights;
    updateRecipe(itemType: number, clearResults?: boolean, preserveScroll?: boolean): void;
    refreshNormalCraftView(preserveScroll?: boolean, preserveSelections?: boolean): void;
    refreshBulkCraftView(preserveScroll?: boolean, preserveQuantity?: boolean, preserveSelections?: boolean): void;
    refreshDismantleView(preserveScroll?: boolean, preserveQuantity?: boolean, preserveSelections?: boolean): void;
    refreshVisibleCraftingViews(preserveScroll?: boolean): void;
    private rebuildNormalContent;
    private restoreScrollPosition;
    private getPreSelectedItems;
    private isSplitComponent;
    private getSplitSelection;
    private setSplitSelection;
    private clearSplitSelection;
    private collectCurrentSplitSelectionIds;
    private repairSplitSelection;
    private reportSelectionUnavailable;
    private resolveComponentSelection;
    private collectCurrentNormalSelectionIds;
    private toTitleCase;
    private formatEnumName;
    private updateCraftButtonState;
    private updateCounter;
    private buildOutputCard;
    private getSemanticTooltip;
    private appendSectionHeader;
    private addBaseComponentSection;
    private addComponentSection;
    private createStaticContentContainer;
    private createScrollPort;
    private createSection;
    private createLabelRow;
    private createItemsContainer;
    private makeFullWidthWrapper;
    private appendMissing;
    private addItemRow;
    private addSplitItemRow;
    private buildBulkContent;
    private buildDismantleContent;
    private buildDismantleHeaderCard;
    private addDismantleHelpBox;
    private addDismantleRequiredSection;
    private addDismantleTargetSection;
    private addDismantleRequiredRow;
    private appendBulkDurabilityControls;
    private appendDismantleDurabilityControls;
    private getMaxUsesText;
    private addDismantleTargetRow;
    private createSelectionRow;
    private applySelectionRowState;
    private getCurrentHotkeyText;
    private getActivationModeText;
    private resetHelpBoxStates;
    private addHelpBox;
    private addNormalHelpBox;
    private addBulkHelpBox;
    private addBulkMaterialsHeader;
    private addBulkComponentSection;
    private getBulkToolSelection;
    private getBulkUsedSelection;
    private addBulkItemRow;
    private addBulkUsedRow;
    private addBulkToolRow;
    private getCraftDurabilityLoss;
    private getDismantleDurabilityLoss;
    private getRemainingUses;
    private computeBulkDurabilityMax;
    private prepareBulkPinnedSelections;
    private computeBulkLimits;
    private computeBulkMax;
    private computeDismantleMax;
    private hasDismantleDurabilityLimit;
    private getIncludedDismantleItems;
    private updateBulkMaxDisplay;
    private adjustBulkQty;
    private updateBulkCraftBtnState;
    private bulkCrafting;
    private hasIncompleteBulkToolSelection;
    private onBulkCraft;
    resolveForBulkCraft(itemType: ItemType, excludedIds: Set<number>, sessionConsumedIds?: ReadonlySet<number>): {
        required: Item[];
        consumed: Item[];
        base: Item | undefined;
    } | null;
    private getBulkExcludedIds;
    private resolveBulkCraftSelection;
    private getBulkToolCandidateOrder;
    private findBulkCandidates;
    private bcGetOrCreateTooltip;
    private bcShowTooltip;
    private bcShowTextTooltip;
    private bcHideTooltip;
    private bcPositionTooltip;
    private bcFillTooltipForItem;
    private bcFillTooltipForText;
    private createInfoIcon;
    private bcAppendTooltipContent;
    private bcTooltipDivider;
    private getTypeName;
    private findMatchingItems;
    private crafting;
    private onCraft;
    private showValidationError;
}
export {};
