import Component from "@wayward/game/ui/component/Component";
import { ItemType, RecipeLevel } from "@wayward/game/game/item/IItem";
import type Item from "@wayward/game/game/item/Item";
type CraftCallback = (itemType: ItemType, tools: Item[] | undefined, consumed: Item[] | undefined, base: Item | undefined) => Promise<void>;
type BulkCraftCallback = (itemType: ItemType, quantity: number, excludedIds: Set<number>) => Promise<void>;
export interface IBetterCraftingSettings {
    activationMode: "holdHotkeyToBypass" | "holdHotkeyToAccess";
    activationHotkey: "Shift" | "Control" | "Alt";
    unsafeBulkCrafting: boolean;
}
type SettingsAccessor = () => IBetterCraftingSettings;
export interface ICraftDisplayResult {
    success: boolean;
    item?: Item;
    itemType: ItemType;
}
export declare const STAMINA_COST_PER_LEVEL: Partial<Record<RecipeLevel, number>>;
export default class BetterCraftingPanel extends Component {
    itemType: number;
    private scrollContent;
    private recipe?;
    private onCraftCallback;
    private onBulkCraftCallback;
    private getSettings;
    private craftBtn;
    private validationMsg?;
    private selectedItems;
    private sectionCounters;
    private _pendingSelectionIds;
    private bcTooltipEl;
    private _hoveredItem;
    private _hoveredDisplayName;
    private _hoveredMouseX;
    private _hoveredMouseY;
    private shiftHeld;
    private _itemContainerEls;
    private _resizeObserver;
    private _bodyEl;
    private _outputCardEl;
    private activeTab;
    private normalTabBtn;
    private bulkTabBtn;
    private normalBody;
    private normalFooter;
    private bulkBody;
    private bulkFooter;
    private normalResultsEl;
    private bulkResultsEl;
    private bulkExcludedIds;
    private _lastBulkItemType;
    private bulkQuantity;
    private bulkQtyInputEl;
    private bulkMaxLabel;
    private bulkCraftBtnEl;
    private bulkScrollContent;
    private _bulkItemContainerEls;
    private _bulkOutputCardEl;
    private _bulkBodyEl;
    private _bulkContentDirty;
    private bulkStopBtn;
    private bulkQtyRow;
    private bulkProgressEl;
    private onBulkAbortCallback;
    private get activationHotkey();
    private isConfiguredHotkey;
    private updateActivationHotkeyState;
    private readonly _onShiftDown;
    private readonly _onShiftUp;
    private readonly _onBlur;
    constructor(onCraft: CraftCallback, onBulkCraft: BulkCraftCallback, getSettings: SettingsAccessor);
    destroyListeners(): void;
    private switchTab;
    showPanel(): void;
    hidePanel(): void;
    get panelVisible(): boolean;
    setBulkAbortCallback(cb: (() => void) | null): void;
    onBulkCraftStart(total: number): void;
    setBulkProgress(current: number, total: number): void;
    onBulkCraftEnd(): void;
    private updateHighlights;
    private clearHighlights;
    updateRecipe(itemType: number, clearResults?: boolean): void;
    private getPreSelectedItems;
    private toTitleCase;
    private formatEnumName;
    private updateCraftButtonState;
    private updateCounter;
    private buildOutputCard;
    private addBaseComponentSection;
    private addComponentSection;
    private createSection;
    private createLabelRow;
    private createItemsContainer;
    private makeFullWidthWrapper;
    private appendMissing;
    private _updateItemListHeights;
    private addItemRow;
    private buildBulkContent;
    private addBulkHelpBox;
    private addBulkMaterialsHeader;
    private addBulkComponentSection;
    private addBulkItemRow;
    private computeBulkLimits;
    private computeBulkMax;
    private updateBulkMaxDisplay;
    private adjustBulkQty;
    private updateBulkCraftBtnState;
    private bulkCrafting;
    private onBulkCraft;
    resolveForBulkCraft(itemType: ItemType, excludedIds: Set<number>): {
        tools: Item[];
        consumed: Item[];
        base: Item | undefined;
    } | null;
    private bcGetOrCreateTooltip;
    private bcShowTooltip;
    private bcHideTooltip;
    private bcPositionTooltip;
    private bcFillTooltipForItem;
    private bcTooltipDivider;
    clearResults(): void;
    showSingleCraftResult(result: ICraftDisplayResult): void;
    showBulkCraftResults(results: ICraftDisplayResult[]): void;
    private createResultsContainer;
    private clearResultsContainer;
    private syncResultsVisibility;
    private renderSingleCraftResult;
    private renderBulkCraftResults;
    private createResultsTitle;
    private getDisplayName;
    private getTypeName;
    private findMatchingItems;
    private crafting;
    private onCraft;
    private showValidationError;
}
export {};
