import Component from "@wayward/game/ui/component/Component";
import { ItemType } from "@wayward/game/game/item/IItem";
import type Item from "@wayward/game/game/item/Item";
type CraftCallback = (itemType: ItemType, tools: Item[] | undefined, consumed: Item[] | undefined, base: Item | undefined) => Promise<void>;
export default class PrecisionCraftingPanel extends Component {
    itemType: number;
    private scrollContent;
    private recipe?;
    private onCraftCallback;
    private panelTitle;
    private craftBtn;
    private selectedItems;
    private sectionCounters;
    constructor(onCraft: CraftCallback);
    showPanel(): void;
    hidePanel(): void;
    get panelVisible(): boolean;
    private updateHighlights;
    private clearHighlights;
    updateRecipe(itemType: number): void;
    private toTitleCase;
    private formatEnumName;
    private updateCraftButtonState;
    private updateCounter;
    private addBaseComponentSection;
    private addComponentSection;
    private createSection;
    private createLabelRow;
    private appendMissing;
    private addItemRow;
    private getTypeName;
    private findMatchingItems;
    private crafting;
}
export {};
